# DO NOT ADD OR CREATE ANY NEW CELLS
## DO NOT ADD OR CREATE ANY NEW CELLS
### DO NOT ADD OR CREATE ANY NEW CELLS
#### DO NOT ADD OR CREATE ANY NEW CELLS

### YOU HAVE TO RUN ALL THESE CELLS BEFORE MOVING ON TO YOUR QUESTIONS. IF YOU ENCOUNTER ANY ERRORS JUST RESTART THE KERNEL

In [1]:
#Do not modify this cell
#Run this Cell
import pandas as pd
%load_ext sql

In [2]:
q1 = pd.read_csv('q1.csv', sep = '\t')
q2 = pd.read_csv('q2.csv', sep = '\t')
q3 = pd.read_csv('q3.csv', sep = '\t')
q4 = pd.read_csv('q4.csv', sep = '\t')
q5 = pd.read_csv('q5.csv', sep = '\t')

FileNotFoundError: [Errno 2] No such file or directory: 'q1.csv'

In [ ]:
%sql sqlite:///bookstore.sqlite

# Here are your questions
You are the database administrator for an online bookstore. The bookstore database has several tables that store information about books, authors, customers, orders, and order items. Your task is to create a set of SQL queries to extract useful information from this database.
- The name of the table are authors, books, customers, order_items, orders, reviews
- Always start your answers with this line `%%sql result <<`. Each question has its own format. For example, Question One would be `%%sql q1_result <<` and so on like that.
- Then start writing your query on the next line for example, Question 2 would be
    ```
%%sql q2_result <<
    select * from orders
    ```

- If you do not follow these instructions your score will not count.

#### 1. Retrieve a list of the top 5 most popular books based on the number of times they have been ordered. Also order by author name in descending order

In [3]:
#Run this cell to see the expected output
#do not modify this cell
print('This is the expected output')
q1

This is the expected output

NameError: name 'q1' is not defined

- **Your column names must match the expected output**
- **clear everything in the cell below and write your sql query there.** 
- Start your answer by typing this exactly as the first line.
```
%%sql q1_result <<

In [4]:
%%sql q1_result <<
Select b.title, a.name as author_name, Count(oi.book_id) as order_count
from books as b
Join authors as a
on b.author_id = a.author_id
Join order_items as oi
On b.book_id = oi.book_id
GROUP BY b.title
ORDER BY order_count DESC, author_name DESC
LIMIT 5;

Traceback (most recent call last):
  File "C:\Users\USER\miniconda3\Lib\site-packages\sql\magic.py", line 196, in execute
    conn = sql.connection.Connection.set(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\miniconda3\Lib\site-packages\sql\connection.py", line 82, in set
    raise ConnectionError(
sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [5]:
#Run this cell to check your output
#do not modify this cell
print('This is the output of your query')
q1_result.DataFrame()

This is the output of your query

NameError: name 'q1_result' is not defined

In [6]:
#do not modify this cell
assert q1_result.DataFrame().equals(q1)

NameError: name 'q1_result' is not defined

#### 2. Calculate the total revenue generated by each author from the sales of their books.

In [6]:
#Run this cell to see the expected output
#do not modify this cell
print('This is the expected output')
q2['total_revenue'] = q2['total_revenue'].apply(lambda x: round(x, 2) )
q2

This is the expected output

NameError: name 'q2' is not defined

- **Your column names must match the expected output**
- **clear everything in the cell below and write your sql query there.** 
- Start your answer by typing this exactly as the first line.
```
%%sql q2_result <<

In [7]:
%%sql q2_result <<
Select a.name as author_name,
sum(b.price * oi.quantity) as total_revenue
FROM order_items oi
Join books b on oi.book_id = b.book_id
Join authors a ON b.author_id =a.author_id
GROUP BY author_name, a.author_id
Order by total_revenue DESC;

Traceback (most recent call last):
  File "C:\Users\USER\miniconda3\Lib\site-packages\sql\magic.py", line 196, in execute
    conn = sql.connection.Connection.set(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\miniconda3\Lib\site-packages\sql\connection.py", line 82, in set
    raise ConnectionError(
sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [8]:
#Run this cell to check your output
#do not modify this cell
print('This is the output of your query')
q2result = q2_result.DataFrame()
q2result['total_revenue'] = q2result['total_revenue'].apply(lambda x: round(x, 2) )
q2result

This is the output of your query

NameError: name 'q2_result' is not defined

In [9]:
#do not modify this cell
assert q2result.equals(q2)

NameError: name 'q2result' is not defined

#### 3. Identify the top 5 customers who have placed the most orders. Also order by customer name in descending order

In [11]:
#Run this cell to see the expected output
#do not modify this cell
print('This is the expected output')
q3

This is the expected output

NameError: name 'q3' is not defined

- **Your column names must match the expected output**
- **clear everything in the cell below and write your sql query there.** 
- Start your answer by typing this exactly as the first line.
```
%%sql q3_result <<

In [12]:
%%sql q3_result <<
SELECT c.name as customer_name, count(o.order_id) as order_count
FROM customers c
JOIN orders o ON  c.customer_id = o.customer_id
GROUP BY c.name
ORDER BY order_count DESC, customer_name DESC
LIMIT 5;

Traceback (most recent call last):
  File "C:\Users\USER\miniconda3\Lib\site-packages\sql\magic.py", line 196, in execute
    conn = sql.connection.Connection.set(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\miniconda3\Lib\site-packages\sql\connection.py", line 82, in set
    raise ConnectionError(
sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [13]:
#Run this cell to check your output
#do not modify this cell
print('This is the output of your query')
q3_result.DataFrame()

This is the output of your query

NameError: name 'q3_result' is not defined

In [14]:
#do not modify this cell
assert q3_result.DataFrame().equals(q3)

NameError: name 'q3_result' is not defined

#### 4. Find all orders that contain book with book_id = 1.

In [15]:
#Run this cell to check your output
#do not modify this cell
print('This is the expected output')
q4

This is the expected output

NameError: name 'q4' is not defined

- **Your column names must match the expected output**
- **clear everything in the cell below and write your sql query there.** 
- Start your answer by typing this exactly as the first line.
```
%%sql q4_result <<

In [37]:
%%sql q4_result <<
Select oi.order_id,
c.name as customer_name,
o.order_date from order_items oi
JOIN orders o ON oi.order_id = o.order_id
JOIN customers c ON o.customer_id = c.customer_id
Where oi.book_id = 1

 * sqlite:///bookstore.sqlite
Done.
Returning data to local variable q4_result

In [38]:
#Run this cell to check your output
#do not modify this cell
print('This is the output of your query')
q4_result.DataFrame()

This is the output of your query

   order_id  customer_name  order_date
0         1  Alice Johnson  2023-05-01
1         5   Eva Martinez  2023-05-05
2        13   Eva Martinez  2023-05-15
3        21  Charlie Brown  2023-06-20

In [39]:
#do not modify this cell
assert q4_result.DataFrame().equals(q4)

#### 5. Select detailed review information of the Least 5 Books based on ratings, including book title, author name, review rating, and review text.

In [40]:
#Run this cell to see the expected output
#do not modify this cell
print('This is the expected output')
q5

This is the expected output

,review_id,book_title,author_name,rating,review_text
0,1,1984,George Orwell,5,A timeless masterpiece.
1,2,Pride and Prejudice,Jane Austen,4,A wonderful love story.
2,3,Harry Potter and the Philosophers Stone,J.K. Rowling,5,An incredible journey of magic and friendship.
3,4,Adventures of Huckleberry Finn,Mark Twain,4,A fascinating adventure.
4,5,The Hobbit,J.R.R. Tolkien,5,An epic tale of heroism.

- **Your column names must match the expected output**
- **clear everything in the cell below and write your sql query there.** 
- Start your answer by typing this exactly.
```
%%sql q5_result <<

In [41]:
%%sql q5_result <<
Select r.review_id,
b.title as book_title,
a.name as author_name,
r.rating,
r.review_text
FROM reviews r
JOIN books b ON r.book_id =b.book_id
JOIN authors a ON b.author_id =a.author_id
ORDER BY r.review_id ASC
LIMIT 5;

 * sqlite:///bookstore.sqlite
Done.
Returning data to local variable q5_result

In [42]:
#Run this cell to check your output
#do not modify this cell
print('This is the output of your query')
q5_result.DataFrame()

This is the output of your query

,review_id,book_title,author_name,rating,review_text
0,1,1984,George Orwell,5,A timeless masterpiece.
1,2,Pride and Prejudice,Jane Austen,4,A wonderful love story.
2,3,Harry Potter and the Philosophers Stone,J.K. Rowling,5,An incredible journey of magic and friendship.
3,4,Adventures of Huckleberry Finn,Mark Twain,4,A fascinating adventure.
4,5,The Hobbit,J.R.R. Tolkien,5,An epic tale of heroism.

In [44]:
#do not modify this cell
assert q5_result.DataFrame().equals(q5)